---
title: johnnyblog.github.io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: johnnyblog
url: https://johnnyblog.github.io
description: Notes,  How-Tos, and FAQs
permalink: "/:title/"
highlighter:
plugins:
- jekyll-redirect-from
whitelist:
- jekyll-redirect-from
jekyll-redirect-from: true
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
exclude:
- README.md
- Gemfile.lock
- Gemfile
- Rakefile
- vendor
